# CHANGING ANYTHING HERE MAY BREAK THE APPLICATION
# IF CHANGES NEED TO BE MADE RERUN THE CONFIGURATION SCRIPT

SECRET_KEY = 'PASSWORD'
PORT = 22885
CERT_PATH = '/home/kali/c2/Vandals/VANDAL-PRD/v1/utils/certificates/cert.pem'
KEY_PATH = '/home/kali/c2/Vandals/VANDAL-PRD/v1/utils/certificates/key.pem'
MONGO_PATH = '127.0.0.1'
MONGO_PORT = 27017
